/** Defaults por formType — usados ao inicializar instâncias de ambiente */
export const defaultsPorFormType = {
  cozinha: {
    granito: null,
    granitoadaptar: null,
    tanque: null,
    tanqueMoveis: null,
    eletrosDefined: null,
    eletros: [],
    observacoes: '',
  },
  dormitorio: {
    tamanhoCama: null,
    camaLargura_cm: null,
    camaComprimento_cm: null,
    tv: null,
    tvPontoFinal: null,
    tv_polegadas: null,
    tv_modelo: '',
    tv_largura_cm: null,
    tv_altura_cm: null,
    tv_profundidade_cm: null,
    tv_link: '',
    cortineiro: null,
    cortieneiroInstalado: null,
    rodape: null,
    observacoes: '',
  },
  home: {
    eletronicos: null,
    eletronicosList: [],
    tv: null,
    tvPontoFinal: null,
    tv_polegadas: null,
    tv_modelo: '',
    tv_largura_cm: null,
    tv_altura_cm: null,
    tv_profundidade_cm: null,
    tv_link: '',
    cortineiro: null,
    cortieneiroInstalado: null,
    rodape: null,
    observacoes: '',
  },
  banheiro: {
    granito: null,
    granitoadaptar: null,
    cuba: null,
    observacoes: '',
  },
  outros: {
    granito: null,
    granitoadaptar: null,
    tanque: null,
    tanqueMoveis: null,
    tv: null,
    tvPontoFinal: null,
    tv_polegadas: null,
    tv_modelo: '',
    tv_largura_cm: null,
    tv_altura_cm: null,
    tv_profundidade_cm: null,
    tv_link: '',
    cortineiro: null,
    cortieneiroInstalado: null,
    rodape: null,
    tamanhoCama: null,
    camaLargura_cm: null,
    camaComprimento_cm: null,
    eletrosDefined: null,
    eletros: [],
    cuba: null,
    eletronicos: null,
    eletronicosList: [],
    observacoes: '',
  },
}

/** @type {object} */
export const estadoInicial = {
  _meta: {
    etapaAtual: 'identificacao',
    origemNavegacao: null,
    criadoEm: null,
    atualizadoEm: null,
  },

  identificacao: {
    nome: '',
    contrato: '',
    cep: '',
    logradouro: '',
    complemento: '',
    bairro: '',
    cidade: '',
    uf: '',
    telefone: '',
  },

  ambientesSelecionados: [],

  global: {
    g1_temIluminacaoExterna: null,
    g1_ambientes: [],
    g2_temReforma: null,
    g2_ambientes: [],
    g2_1_temReboco: null,
    g2_2_temRevestimento: null,
    g3_pontosNaPosicaoFinal: null,
    g3_ambientesPendentes: [],
    g4_temRebaixo: null,
    g4_ambientes: [],
  },

  respostasPorAmbiente: {},
}
